app = 'cubesolve-webgl'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile.webgl"

[deploy]
  release_command = "sh -c 'echo \"=============================================\" && echo \"  Deploying CubeSolve-WebGL v$(cat src/cube/resources/version.txt)\" && echo \"=============================================\" '"

[http_service]
  internal_port = 8766
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
