# fly.toml app configuration file generated for cubesolve on 2026-02-25T21:46:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cubesolve'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile-fly"

[deploy]
  release_command = "sh -c 'echo \"=============================================\" && echo \"  Deploying CubeSolve v$(cat src/cube/resources/version.txt)\" && echo \"=============================================\" '"

[http_service]
  internal_port = 8765
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'
