# Auto-deploy DEV app on push to web1
# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy (Dev)
on:
  push:
    branches:
      - web1
jobs:
  deploy:
    name: Deploy dev app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app cubesolve-boaz-dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
